name: Setup PostgreSQL and test igor

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Postgres database
        uses: Daniel-Marynicz/postgresql-action@master
        with:
          postgres_image_tag: "14.5"
          app_user: igor
          app_user_password: igor
          app_db: igor
      - name: Setup Go environment
        uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
      - name: build
        run: go test -v ./...
      - name: test
        run: go test -v ./...
